from textacy import extract as ext
from textacy import Doc
import re

import sys
import spacy
from spacy import displacy

corref = spacy.load('en_coref_md')
print("loaded coref")
def resolve_correfs(text):
    #return text #TODO
    doc = corref(text)

    print(doc._.has_coref)
    print(doc._.coref_clusters)
    return doc._.coref_resolved

propn = "PROPN"
def span_is_interesting(item):
    return item.root.pos_ == propn

def subject_to_subtree(item):
    return ' '.join([t.text for t in item.root.subtree])

def extract_triples(text):
    doc = Doc(text, lang='en_core_web_sm')
    for item in ext.subject_verb_object_triples(doc):
        if span_is_interesting(item[0]) or span_is_interesting(item[2]):
            #print(item)
            exp_sub = subject_to_subtree(item[0])
            sub = ' '.join([x.text for x in item[0]])
            verb = ' '.join([x.text for x in item[1]])
            obj = ' '.join([x.text for x in item[2]])
            exp_obj = subject_to_subtree(item[2])

            sub_pn = ""
            if span_is_interesting(item[0]):
                sub_pn = sub

            obj_pn = ""
            if span_is_interesting(item[2]):
                obj_pn = obj

            print([sub_pn, exp_sub, verb, obj_pn, exp_obj])

nlp = spacy.load("en_core_web_sm")
print("loaded web_sm")
def visualize(text):
    doc = nlp(text)
    sentence_spans = list(doc.sents)
    #displacy.serve(sentence_spans, style="ent")
    displacy.serve(sentence_spans, style="dep")

def sanitize_string(var1):
    var1 = re.sub(r', [+-]\d+\.\d+%', "", var1) #ticker value
    var1 = re.sub(r'[Ii]nc.', "Inc", var1) #Inc sentence
    var1 = re.sub(r'\([^()]*\)', " ", var1) #perens
    var1 = re.sub(r'(\\u201c)|(\\u201d)|(\\u201f)|(\\u2033)|(\\u2036)', "\"", var1)
    var1 = re.sub(r'(\\u2018)|(\\u2019)|(\\u201b)|(\\u2032)|(\\u2035)', "\'", var1)
    var1 = re.sub(r'\\u[0-9a-f]{4}', "", var1)
#var1 = var1.replace("%", " percent")
    return var1

if __name__ == '__main__':
    var1 = r'''
    American Airlines Group Inc. AAL, +0.03% disclosed Monday that its expects the Federal Aviation Administration's grounding of Boeing Co.'s BA, +1.02% 737 MAX aircraft to continue to cause "significant disruption" to its customers and financial costs to the airline. The company said, however, that the financial costs of the disruption "cannot be forecasted at this time," as they will depend on a number of factors, including the period of time of the grounding and the circumstances related to the reintroduction of the aircraft. American said in a filing with the SEC that its fleet included 24 Boeing MAX 8 aircraft, with an additional 76 aircraft on order. Prior to the grounding, it had been operating on average about 90 flights a day involving the grounded aircraft, with flight cancellations announced through April 24, so far. American's stock slipped 0.1% in premarket trade. It has shed 4.8% year to date, while Boeing shares have rallied 12.3%, the NYSE Arca Airline Index XAL, -0.33% has gained 4.5% and the Dow Jones Industrial Average DJIA, +0.23% has advanced 9.3%.

Have we seen the worst of the great yield-inversion crisis of 2019?On the heels of a largely drama-free session, there\u2019s an appetite for risk in the air for Tuesday, with stocks higher, though that inversion of 10-year Treasury note TMUBMUSD10Y, +1.32%  and 3-month T-bills yields is still sticking. Recent market action has certainly schooled plenty where that subject is concerned.As a recap, last week\u2019s equity selloff was by the inversion of the yield curve\u2014an unusual condition that occurs when short-dated rates of government debt rise above their longer-term counterparts. Such inversions have accurately predicted recessions in the past. Buying of longer-date bonds implies a dim outlook on the economy on the part of investors. (If you\u2019re still not clear on inversions here\u2019s our guide).But, that \u201csmell of panic we experienced on Friday seems to have dissipated,\u201d said Jeffrey Halley, senior market analyst at OANDA, in a note to clients. Others would agree that a fire sale of stocks such as seen last week may have been hasty.A batch of data coming Tuesday might offer more clarity on where we are on that recession-o-meter.Onto our call of the day, from Adam Kobeissi, founder and editor in chief of The Kobeissi Newsletter, who advises investors to keep a wary eye on the S&P 500, which failed to hold the important 2,800 support level on Monday. And that could open the door to a sizable move lower for the index, he says.\u201cWe watch 2,760-2,785 as the next major technical level which will lead to a gap lower to 2,700 if broken. Overall, a 7-10% drop from today\u2019s close is highly likely for the S&P 500 and our subscribers have been alerted about this shorting opportunity,\u201d said Kobeissi, in comments to MarketWatch.He explains that Wall Street is no longer getting support from the two main drivers of equities since the lows of Christmas Eve\u2014hopes for a trade deal that have been \u201coverpriced\u201d into stocks and increasingly dovish Fed policy.\u201cAdditionally, and more importantly, the reason for a more dovish Fed is because of slowing global economic growth which means that the economic deterioration bearishness will significantly dominate the bullishness from less rate increases,\u201d he said.Here\u2019s his S&P chart showing how he thinks this will play out:Kobeissi says if things go the other way, and the market ends bucking his theory, investors should watch to make sure 2,815 holds as \u201cthat is the bears\u2019 strongest resistance level.\u201dChiming in elsewhere, Reformed Broker\u2019s Josh Brown wondered on his blog whether bulls got too excited and are now \u201ctrapped\u201d above that 2,815 level. He highlights a chart from BayCrest Partners Jonathan Krinsky, who said the fact that the S&P closed below the 2,815 so fast after breaking above it on March 15, and after five failed attempts, bodes badly in the short-term.
Krinsky cited the phrase: \u2018from false moves comes fast moves in the opposite direction\u2019 adding: \u201cIf Bulls are able to quickly recover and get back above 2,815, that would be encouraging, but for now, the recent action should warrant some caution.\u201dRead: Guggenheim\u2019s Minerd says Fed won\u2019t be able to resist urge to raise rates in 2019So far, the S&P 500 SPX, +0.47%  is trucking along higher, along with the Dow DJIA, +0.46%  and Nasdaq COMP, +0.62%  . Read more in Market Snapshot.The dollar DXY, -0.10% is flat, gold US:GCU8 is weaker and crude US:CLU8 is little changed.Europe stocks SXXP, +0.58%  are moving up across the board. Asian equities were mixed, with the Nikkei NIK, +0.82%  rebounding 2% after Monday\u2019s drop, but the Shanghai Composite sliding 1.5%.Callum Thomas, founder of research firm Topdown Charts, provides our chart of the day, which he says reveals a \u201cbull market in pessimism.\u201dThe above chart comes after he tallied up what he was finding with regards to bearish views on equities versus bullish views on bonds.\u201cAs you can see, we\u2019re in uncharted territory here. Fear has taken over on the outlook (weaker PMIs, inverting yield curve, geopolitics, etc etc),\u201d he said, adding that it\u2019s \u201centirely possible that the \u2018bull market in pessimism\u2019 is overdone.\u201dSamsung 005930, -0.45%  fell in Korea after warning that its first-quarter results will miss forecasts thanks to weak semiconductor sales, though that hasn\u2019t seem to hit tech elsewhere. The company, which supplies chips for Apple AAPL, +0.40%  iPhones are calling it tech\u2019s inverted-yield curve and a warning of hard times to come.Opinion: Apple leaves a lot of questions about its subscription services unansweredA group of activist investors are targeting Bed Bath & Beyond BBBY, +0.17% with a bid to launch a proxy fight to replace the entire board of directors and get the retailer back on track. Those shares are flying high.Ride-hailing service Uber is buying Middle East rival Careem for $3.1 billion.Boeing BA, +0.31%  rival Airbus AIR, +1.12%  signed a multibillion-dollar deal with China.Lawyer Michael Avenatti tweeted early Tuesday that he \u201cnever attempted to extort Nike\u201d and the truth about the sport\u2019s retailers \u201ccrime and coverup\u201d will be revealed. Nike shares were put through the wringer Monday after a drama-filled day that ended up with arrest of the former Stormy Daniels\u2019 lawyer.In London, U.K. Prime Minister Theresa May was handed another defeat via an amendment that let\u2019s Parliament to express its view on how Brexit should now unfold. 
The late-night Monday vote resulted in the exit of several lawmakers.Housing starts fell 9% in February and remain well under yea-ago levels, while Case-Shiller home prices and consumer confidence are still to come. We\u2019ll also hear from a handful of Fed speakers\u2014Philadelphia Fed President Patrick Harker and San Francisco Fed President Mary Daly later. Meanwhile, Boston Fed Pres. Eric Rosengren told a conference in Hong Kong that the central bank should consider buying Treasury bills in the next phase of its balance-sheet program.\u201cThe notion that you could gut the entire ACA [Affordable Care Act] and not wreak havoc on the lives of millions of people is insane. It is now part of the plumbing of the health-care system.\u201c\u2014That was University of Michigan law school professor Nicholas Bagley in comments on health services research blog The Incidental Economist after the Justice Dept. said in a legal filing Monday that it agrees with a Texas district court\u2019s ruling that the ACA, otherwise known as Obamcare, is unconstitutional. That massive overhaul of the U.S. health care system, became law in March 2010 under the Obama administration.$175 trillion\u2014That\u2019s the total value of global stocks and bonds outstanding, eight times higher than it was in 1990\u2014at $23 trillion, notes Bank of America Merrill Lynch in its \u201cThundering Word\u201d note to clients sent out Tuesday. Global assets, it says, are twice the size of the global economy.Storied mixed martial arts champ Conor McGregor says his fighting days are overNo breaks for Venezuela, suffering fresh blackoutsNASA suffers wardrobe failure, cancels all-female spacewalkFans underwhelmed by Mattel\u2019s MAT, -0.38%  BTS boy-band dolls take to social media:Need to Know starts early and is updated until the opening bell, but sign up here to get it delivered once to your email box. Be sure to check the Need to Know item. The emailed version will be sent out at about 7:30 a.m. Eastern.Follow MarketWatch on Twitter, Instagram, Facebook.Providing critical information for the U.S. trading day. Subscribe to MarketWatch's free Need to Know newsletter. Sign up here.'''
#The U.S. Department of Housing and Urban Development on Thursday said it's charging Facebook FB, -0.19% with violating the Fair Housing Act by \"encouraging, enabling and causing\" discrimination by restricting who can view housing-related ads on the social-media platform. \"Using a computer to limit a person's housing choices can be just as discriminatory as slamming a door in someone's face,\" HUD Secretary Ben Carson said in a statement.
#WASHINGTON, March 28, 2019 /PRNewswire/ -- Google, Facebook, General Motors and Walmart, along with over 300 other companies, launched the Renewable Energy Buyers Alliance (REBA) today\u2014the largest group of corporate renewable energy buyers in the United States. By working to unlock the marketplace for organizations to buy renewable energy, REBA hopes to bring more than 60 gigawatts of new renewables online in United States by 2025.With offices in Washington, DC and Boulder, Colorado, the new membership organization will span diverse industries and businesses, whose leadership circle alone represents annual revenues of $1 trillion and over 1% of US annual electricity consumption (48 terawatt-hours).\"Every enterprise\u2014whether it's a bakery, a big-box retailer, or a data center\u2014should have an easy and direct path to buy clean energy. Ultimately, sourcing clean energy should be as simple as clicking a button,\" said Michael Terrell, head of Energy Market Strategy, Google, and REBA's first board chair.REBA's vision of tomorrow's energy marketplace is simple and powerful: a resilient carbon-free energy system where every organization has an easy and cost-effective path to buying renewable energy. Commercial and industrial energy users were responsible for more than 2 billion tons of greenhouse gases from energy use in 2018.
#Mitigating these emissions is part of the reason why over 70% of Fortune 100 companies have set greenhouse gas emissions reduction targets or renewable energy purchasing goals.\"Today's REBA launch demonstrates that large energy buyers from across every sector are committed to doing their part to solve this problem,\" said Rob Threlkeld, global manager, Sustainable Energy/Supply Reliability at General Motors.Membership is available to nonresidential energy buyers, clean energy developers and other service providers. The association aims to open energy markets and offer greater choice for corporate energy buyers, focusing on innovations in policy, markets and technology as well as educational training.\"Never before has such a diverse group of organizations, from every industry, come together to form an association with a single, market-focused, mission-driven vision of a zero-carbon energy future,\" said REBA's inaugural CEO and former US Air Force executive, Miranda Ballentine.REBA was originally founded in 2014 as a partnership between four NGOs\u2014Rocky Mountain Institute, World Wildlife Fund, World Resources Institute, and Business for Social Responsibility.
#    The big demand for shares of Lyft Inc., one of the most anticipated IPOs of the tech unicorns, is the unofficial opening of this year\u2019s IPO casino.On Thursday, Lyft priced its Friday public debut at $72 a share, at the high end of an already increased range, giving the ride-hailing-app company a valuation of about $24 billion, on a fully-diluted share basis. Indeed, Lyft\u2019s LYFT, +0.00%  offering ahead of its better-funded rival, Uber Technologies Inc., is an impressive feat, and it will lead the way for a string of long-awaited IPOs of tech unicorns, so-called because of their private valuations of at least $1 billion.But the pricing also shows that many IPO investors don\u2019t care very much about long-term investing, and those buying up initial shares of Lyft, and likely other tech unicorns, are more interested in getting in on a much-hyped deal \u2014 and then getting out quickly.\u201cI think the IPO world has just changed in the last few years, there was always an opportunity to get an allocation, and the notion of the first-day pop. But what the issuer crowd has figured out is that people are lined up for these deals,\u201d said Kurt Schacht, managing director of standards and advocacy at the CFA Institute. \u201cIt\u2019s more like a casino than an actual investment. I worry what that does long term.\u201dRead: Lyft IPO: 5 things to know about the ride-hailing companyThat\u2019s because Lyft, like several recent tech IPOs and surely more to come, has a corporate structure that keeps its founders entrenched with the bulk of voting control, a popular concept in Silicon Valley, which loves to keep its founders in charge, even when things go badly. Lyft, like many tech companies of the current vogue, has issued dual-class shares \u2014 Class A common stock to the public, with one vote per share, and Class B stock, with 20 votes per share, to its founders.According to Lyft\u2019s prospectus, co-founder and Chief Executive Logan Green and co-founder, President and Vice Chairman John Zimmer together own a 49% voting stake with their ownership of Class B shares. That, combined with the shares of 12 other top Lyft executives and directors, will give company insiders 60% voting control upon completion of the IPO.\u201cOur co-founders, individually or together, will be able to significantly influence matters submitted to our stockholders for approval,\u201d Lyft said in its filing with the Securities and Exchange Commission.\n\u201cOur co-founders, individually or together, may have interests that differ from yours and may vote in a way with which you disagree and which may be adverse to your interests.\u201dIf shareholders have any issues, such as if they don\u2019t like the direction of the company, or what executives are doing with the IPO proceeds, etc., their voices won\u2019t matter.
#    \u201cThe verdict is out whether dual-class shares can enhance shareholder value,\u201d said Jason Schloetzer, an associate professor of business administration at Georgetown University\u2019s McDonough School of Business. \u201cIt\u2019s not necessarily a bad thing, but you can have internet companies thrive without requiring dual-class structures.\u201dLyft made a token effort to improve its corporate governance by naming Sean Aggarwal as its non- executive chairman in January. Aggarawal is CEO of Soar Capital, an early stage VC firm.Granted, Lyft\u2019s founders do not appear to be as omnipotent as Mark Zuckerberg is at Facebook FB, -0.19% where the co-founder and CEO still controls about 60% of the votes, or Snap Inc. SNAP, +1.41%  , where co-founder Evan Spiegel and other executives control 96.4% of the vote. (The developer of the Snapchat app last year held a three-minute annual meeting for investors.)Read about Mark Zuckerberg\u2019s iron-fisted rule of Facebook.Both of those companies are under duress with different issues: Facebook\u2019s privacy and data policies, and Snap\u2019s big losses, product issues and an SEC inquiry into its IPO. Investors have their hands tied and can do nothing, except voice their frustration and hope for the best, or vote the only way they can \u2014 by selling their shares.Investors should decide whether they want to trust Lyft\u2019s top executives with most of the company\u2019s control, and that\u2019s the same decision investors must also make for many of the other big tech IPOs coming down the road, including Pinterest PINS, +0.00% , which will offer dual-class shares. While it may work for some investors over a short term, not having any say in one\u2019s investment is not good for the long term.Want this type of analysis sent to your inbox? Subscribe to MarketWatch's free MarketWatch First Takes newsletter. Sign up here.
#The new Apple Card offers only the second-best Apple Pay rewards program of any credit card on the market.
#    Apple AAPL, +0.94% owes Qualcomm QCOM, -2.47% nearly $1 billion in patent rebate payments, says a federal judge.
#    In corporate news, shares of Apple Inc. AAPL, +0.99% finished off by more than 1% after a judge ruled that the iPhone marker infringes a Qualcomm Inc. QCOM, -2.47% patent.
#    Guy Rosen, Facebook\u2019s FB, +0.84%   \u2016vice president for integrity, said in comments posted late Wednesday that the company\u2019s artificial intelligence tools initially failed to catch the shooter\u2019s live video of the terrorist attack Christchurch mosques last week that killed 50 people.
#    On Wednesday, Apple introduced its second generation wireless AirPods.
#
#    .On Wednesday, Apple introduced its second generation wireless AirPods. They will have 50% more talk time, a hands-free \u201chey, Siri!\u201d voice-assistant feature and the option of a wireless charging case. They are, however, just as easy to lose.
#    SAN FRANCISCO, March 22, 2019 /PRNewswire/ -- Pinterest, Inc. (\"Pinterest\") today announced that it has filed a registration statement on Form S-1 with the U.S. Securities and Exchange Commission (\"SEC\") relating to a proposed initial public offering of shares of its Class A common stock. The number of shares to be offered and the price range for the proposed offering have not yet been determined.Goldman Sachs & Co. LLC, J.P. Morgan Securities LLC and Allen & Company LLC will serve as lead joint book-running managers for the offering. BofA Merrill Lynch, Barclays Capital Inc.,  Citigroup Global Markets Inc., Credit Suisse Securities (USA) LLC, Deutsche Bank Securities Inc. and RBC Capital Markets, LLC will also act as book-running managers for the offering.  Robert W. Baird & Co. Incorporated, UBS Securities LLC and Wells Fargo Securities, LLC will serve as co-managers for the offering.The offering will be made only by means of a prospectus. Copies of the preliminary prospectus relating to the offering, when available, may be obtained from Goldman Sachs & Co. LLC, Prospectus Department, 200 West Street, New York, NY 10282, telephone: 1-866-471-2526 or by emailing Prospectus-ny@ny.email.gs.com; J.P. Morgan Securities LLC, c/o Broadridge Financial Solutions, 1155 Long Island Avenue, Edgewood, NY 11717, phone: 866-803-9204, email: prospectus-eq_fi@jpmchase.com; or Allen & Company, Prospectus Department, 711 Fifth Avenue, 10th Floor, New York, NY 10022, email: dweidlein@allenco.com. A registration statement relating to these securities has been filed with the SEC, but has not yet become effective. These securities may not be sold nor may offers to buy be accepted prior to the time the registration statement becomes effective. This press release shall not constitute an offer to sell or the solicitation of an offer to buy these securities, nor shall there be any sale of these securities in any state or jurisdiction in which such offer, solicitation or sale would be unlawful prior to registration or qualification under the securities laws of any such state or jurisdiction.Contacts:press@pinterest.comir@pinterest.comView original content:http://www.prnewswire.com/news-releases/pinterest-files-registration-statement-with-sec-for-proposed-initial-public-offering-300817263.htmlSOURCE PinterestCopyright (C) 2019 PR Newswire. All rights reserved'''
    #American Airlines 'cannot' forecast costs of grounding of 737 MAX aircraft because of uncertainties
    #American Airlines Group Inc. AAL, +0.03% disclosed Monday that its expects the Federal Aviation Administration's grounding of Boeing Co.'s BA, +1.02% 737 MAX aircraft to continue to cause "significant disruption" to its customers and financial costs to the airline. The company said, however, that the financial costs of the disruption "cannot be forecasted at this time," as they will depend on a number of factors, including the period of time of the grounding and the circumstances related to the reintroduction of the aircraft. American said in a filing with the SEC that its fleet included 24 Boeing MAX 8 aircraft, with an additional 76 aircraft on order. Prior to the grounding, it had been operating on average about 90 flights a day involving the grounded aircraft, with flight cancellations announced through April 24, so far. American's stock slipped 0.1% in premarket trade. It has shed 4.8% year to date, while Boeing shares have rallied 12.3%, the NYSE Arca Airline Index XAL, -0.33% has gained 4.5% and the Dow Jones Industrial Average DJIA, +0.23% has advanced 9.3%."""

    #var1 = """
    #Ford Motor Co. F, -0.27% new chief financial officer Tim Stone, who will succeed retiring CFO Bob Shanks on June 1, will \"certainly need to learn the business,\" but there are positives from his background, analysts at RBC said in a note Thursday. Before Stone's brief stint as CFO of Snap Inc. SNAP, -0.47% he worked in finance at Amazon.com Inc. AMZN, -0.23% for 20 years.'''

    print(var1)
    var1 = sanitize_string(var1)
    print("sanitized:", var1)
    var1 = resolve_correfs(var1)
    print("correfs:", var1)
    extract_triples(var1)
    #visualize(var1)


    
